### PR TITLE
Fix case sensitive value issues for all records by not forcing to lower

### PR DESCRIPTION
**Pull request by ircmaxell**
This PR fixes an issue where case-sensitive records are constantly refreshed (an issue with TXT records, but applies to all other records where internal state and external state are managed separately)

### CODE REVIEW

**Comment by radeksimko** [comment]
Hi @ircmaxell 
do you mind providing an example of case-sensitive record, ideally in the form of an acceptance test?

[RFC434](https://tools.ietf.org/html/rfc4343) does state that DNS servers should be case insensitive.

The lowercasing was [added intentionally](https://github.com/hashicorp/terraform/pull/14130) to address a problem with case-insensitive records which are retuned from the API with different casing, but have the exact same meaning.

Thanks.

**Comment by ircmaxell** [comment]
I can definitely add a test to that regard. I did have some trouble building the package without significant tweaks due to (https://github.com/hashicorp/terraform/pull/15562). I'll try to work through it and get a test in there.

As far as RFC4343, I think you mis-read that RFC. It states that identifiers are compared case-insensitive. It also says that identifiers should be stored in a case sensitive manner as often as possible.

However, for values, it depends on the record type. Specifically 3.3 specifies two possible value-types: 

> domain-name is a domain name represented as a series of labels, and
terminated by a label with zero length.  character-string is a single
length octet followed by that number of characters.  character-string
is treated as binary information, and can be up to 256 characters in
length (including the length octet).

`TXT` records are specified as `one or more character-strings. Therefore it must be treated as binary information. 

As far as `AAAA` record case sensitivity, it's not defined. RFC3596 says they just need to be as defined in RFC3513-2.2, which doesn't specify case.

To be as transparent and compatible with the spec, I would suggest not changing case on anything (which is what RFC1035 actually recommends):

> Systems administrators who enter data into the domain database should take care to represent the data they supply to the domain system in a case-consistent manner if their system is case-sensitive.  The data distribution system in the domain system will ensure that consistent representations are preserved.

**Comment by radeksimko** [comment]
Thanks for the clarification - it does seem I misread the (lengthy) RFC.

This means we'll need to ignore casing depending on the type of the record. I think [`DiffSuppressFunc`](https://github.com/terraform-providers/terraform-provider-aws/blob/7010940953569affc9d221a8bdf9abf5fa134596/aws/resource_aws_instance.go#L95-L104) may be better suited for this purpose as it has access to other fields via `*ResourceData` so we can add some conditionals there.

> I did have some trouble building the package without significant tweaks due to (hashicorp/terraform#15562).

Yep - sorry about that, but DME is one of 3 providers (out of 69 we track in this org) which is "different" to others. I have a plan for bumping the vendored `hashicorp/terraform` across all providers eventually and deal with all discrepancies by deprecating fields which aren't compliant.

I know it's going to cause some pain, but there's historically a lot of uncertainty around what a good provider code looks like and this is just a small piece of a bigger picture we're trying to paint to help developers of new providers in the future. Ideally we'd like all providers to look nearly the same and make it easy for everyone to follow the code no matter which provider they're looking at and unification of formatting helps in that area.

With all that said until we do bump the dependency you shouldn't need to worry about this at all, certainly not in the context of this PR, I think? If you try building it fresh after cloning w/ latest stable go (1.8) it should pick up dependencies from `/vendor` folder which contains `hashicorp/terraform@v0.9.8` (i.e. no strict validation).

https://github.com/terraform-providers/terraform-provider-dme/blob/6e3bdb85c6562b169876f792efe741f34db4b40f/vendor/vendor.json#L377-L482

**Comment by ircmaxell** [comment]
Yeah, that RFC is confusing as heck, it makes several contradictory statements (or seemingly contradictory).

I've actually found the other limitations of the depended-upon library to be a bit hard to work with. For example, it doesn't pass back the rate limiting information so there's no real way to handle that. Additionally, it has limited support for resource creation and no support for anything else (including resource editing which makes it a no-go).

I've looked into "fixing" the underlying library but feel that the API glue code is going to be hard to work with. So I'm tossing around the idea of writing a quick but complete API client library for DME and then building a new (or perhaps retrofitting a fork of this one) provider. I don't know if it's realistic with the bandwidth I have, but it's something on my list.

**Comment by radeksimko** [comment]
> it doesn't pass back the rate limiting information so there's no real way to handle that. 

That is the case for many APIs and/or SDKs, unfortunately. We get around that by just blindly retrying on certain error codes - we have a standard helper for that purpose, see https://github.com/terraform-providers/terraform-provider-aws/blob/7010940953569affc9d221a8bdf9abf5fa134596/aws/resource_aws_instance.go#L490-L505 for example.

> So I'm tossing around the idea of writing a quick but complete API client library for DME and then building a new (or perhaps retrofitting a fork of this one) provider.

It does seem [the library](https://github.com/soniah/dnsmadeeasy) is not actively maintained anymore, so I wouldn't be completely against switching to a different one, if it allows expansion of this provider, but admittedly it may be a bigger job on both sides (provider & library).

But then again - it may complicate testing a little bit, but it shouldn't be a blocker for this particular PR, I think?

**Comment by ircmaxell** [comment]
Yup, we're on the same page. That's why I submitted the PR even though the current state of the provider doesn't suit all my needs (it's good enough for now). This, along with #5 are the two blockers preventing me from adopting fully (well, I'm running a fork now that patches both). 

So definitely can add quick value by landing both these fixes (I will work to add tests for it so it can be landed well) short of the bigger picture end-game...

**Comment by nkatarmal-crest** [comment]
Closing this PR, as provider has been redeveloped and released.

**Pull request closed without merging**
